[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "bcrypt>=5.0.0",
    "pandas>=2.3.3",
    "psycopg2-binary>=2.9.10",
    "streamlit>=1.50.0",
]
